### ISSUE TITLE
thank you! ported to gba

### ISSUE THREAD

**Issue by redthing1** [TheGag96/3ds-hello-dlang#1]
Thanks to the work you did here porting D to 3DS, I was able to build on your work to port D to the GBA as well!

Here is that project: https://github.com/redthing1/gba_dlang

**Comment by TheGag96** [comment]
Whoa!! This is cool! Glad I was able to help haha. Will try building this...

EDIT: Wow, works just great. Any reason you compile your sources separately? All-at-once should still be pretty quick. Or do you just prefer incremental builds?

**Comment by redthing1** [comment]
> Whoa!! This is cool! Glad I was able to help haha. Will try building this...
> 
> EDIT: Wow, works just great. Any reason you compile your sources separately? All-at-once should still be pretty quick. Or do you just prefer incremental builds?

Two reasons:
1. Incremental builds, when working with large projects with lots of objects I generally find it much more efficient
2. Since there is a lot of external code I often use for GBA, it's important for me to maintain the ability to link the D object files with the C object files, like for example a lot of asset packers generate header files, so I'll just write functions in C, and since they're compiled independently with the external functions as extern, I can mix both. I've found it useful.
